/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ArrayOf_Pair = Pair[];

export interface Pair {
  /**
   * @minItems 2
   * @maxItems 2
   */
  denoms: [string, string];
}
